### PR TITLE
Add gg/G scrolling to top/bottom in scrollkey

### PR DESCRIPTION
**Pull request by siboehm**
implemented moving to top/bottom of page with gg/G like in vim

### CODE REVIEW

**Comment by Smile4ever** [comment]
Thank you.

**Comment by siboehm** [comment]
I just noticed that while in vim 'gg' is used to go to the top, many of the pagers like 'less' just use 'g'. I don't know what your preference is, if you want you can keep it as is or I can send you another pull request.

**Comment by Smile4ever** [comment]
I do think it's a good idea to support both options when I make the keys configurable. I have opened #81 for that.

**Comment by Smile4ever** [comment]
The scroll to top/bottom functionality is available in Scrollkey 3.0.

**Pull request merged**
