### PR TITLE
[Scrollkey] Add smooth scrolling behaviour

### LINKED ISSUE #88: [Scrollkey] Enable smooth scrolling
Add an option to enable smooth scrolling on web pages. Should also be a checkbox on the preferences page.

### PR DESCRIPTION
**Pull request by aarohmankad**
Fixes #88.

Can be merged after:

- [x] Smooth scrolling behaviour is added
- [ ] Option to enable/disable smooth scrolling is added to preferences

### CODE REVIEW

**Comment by Smile4ever** [comment]
Thanks looks nice. I will test and report back.

**Comment by Smile4ever** [comment]
Works great. Are you implementing the option yourself or should I implement it?

**Comment by aarohmankad** [comment]
Feel free to implement it yourself, the structure for the options will probably take a little longer to understand than I'd like. Thanks for the quick responses!

**Comment by Smile4ever** [comment]
This is available in Scrollkey 3.0. Thank you!

**Pull request merged**
