### PR TITLE
Always use https in GetArchive

### PR DESCRIPTION
**Pull request by yfdyh000**

### CODE REVIEW

**Comment by Smile4ever** [comment]
This pull request is problematic, since it will no longer recognise HTTP links in some cases. Also, archive.is doesn't support HTTPS well. 6069a23 contains a better fix.

**Comment by yfdyh000** [comment]
Thank you for checking and doing it. Sorry for I didn't test.
I didn't see the problematic for https://archive.is/.

**Comment by Smile4ever** [comment]
It was problematic in the past, but now it seems resolved. If I don't encounter issues within a few days time, I will also switch archive.is over to HTTPS in Get Archive.

**Comment by Smile4ever** [comment]
8ad1485 implements proper archive.is HTTPS support and will be available in Get Archive 2.5.2 which was submitted to Mozilla just now.

**Pull request closed without merging**
