### PR TITLE
Improve Chinese (Simplified) translation

### PR DESCRIPTION
**Pull request by yfdyh000**

### CODE REVIEW

**Comment by Smile4ever** [comment]
Thank you. Was the original translation Chinese simplified as well?

**Comment by yfdyh000** [comment]
This improves the original translation. I'm not sure what you mean.

**Comment by Smile4ever** [comment]
Was the original translation also Simplified Chinese or was it traditional Chinese?

**Comment by yfdyh000** [comment]
It is a Simplified Chinese translation too.

**Pull request merged**
